services:
  db:
    image: postgres:latest
    env_file:
      - ./back_end/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build:
      context: ./back_end
    volumes:
      - ./back_end:/app
    ports:
      - "8000:8000"
    env_file:
      - ./back_end/db.env
      - ./back_end/backend.env
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    build:
      context: ./front_end
    command: npm start
    volumes:
      - ./front_end:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data: